print('Hi guys')
print('My name is Mayara')
print('I learning Python')
print('I am 29 years')
print('I from São Paulo')
print('I love games and animes')
print('I has a beautiful American Pit Bull Terrier')
print('My favorite food is barbecue')
print('My favorite drink is coffee')
print('It is all guys.')